export enum ColorType {
  COLOR_RED = 1,
  COLOR_PURPLE = 2,
  COLOR_BLUE = 3,
  COLOR_CYAN = 4,
  COLOR_GREEN = 5,
  COLOR_YELLOW = 6,
  COLOR_ORANGE = 7,
  COLOR_BROWN = 8,
  COLOR_GREY = 9,
  COLOR_WHITE = 10
}
